package Model;
// Generated Mar 26, 2020 10:12:20 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private Long id;
     private Product product;
     private User user;
     private Date createdAt;
     private Date updatedAt;
     private String content;
     private Integer parentId;

    public Comment() {
    }

	
    public Comment(Product product, User user, String content) {
        this.product = product;
        this.user = user;
        this.content = content;
    }
    public Comment(Product product, User user, Date createdAt, Date updatedAt, String content, Integer parentId) {
       this.product = product;
       this.user = user;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.content = content;
       this.parentId = parentId;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Integer getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }




}


