package Model;
// Generated Mar 26, 2020 10:12:20 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OrderAppDetail generated by hbm2java
 */
public class OrderAppDetail  implements java.io.Serializable {


     private Long id;
     private OrderApp orderApp;
     private ProductSize productSize;
     private Date createdAt;
     private Date updatedAt;
     private long price;
     private int quantity;
     private long totalAmount;

    public OrderAppDetail() {
    }

	
    public OrderAppDetail(OrderApp orderApp, ProductSize productSize, long price, int quantity, long totalAmount) {
        this.orderApp = orderApp;
        this.productSize = productSize;
        this.price = price;
        this.quantity = quantity;
        this.totalAmount = totalAmount;
    }
    public OrderAppDetail(OrderApp orderApp, ProductSize productSize, Date createdAt, Date updatedAt, long price, int quantity, long totalAmount) {
       this.orderApp = orderApp;
       this.productSize = productSize;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.price = price;
       this.quantity = quantity;
       this.totalAmount = totalAmount;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public OrderApp getOrderApp() {
        return this.orderApp;
    }
    
    public void setOrderApp(OrderApp orderApp) {
        this.orderApp = orderApp;
    }
    public ProductSize getProductSize() {
        return this.productSize;
    }
    
    public void setProductSize(ProductSize productSize) {
        this.productSize = productSize;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public long getPrice() {
        return this.price;
    }
    
    public void setPrice(long price) {
        this.price = price;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public long getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(long totalAmount) {
        this.totalAmount = totalAmount;
    }




}


