package Model;
// Generated Mar 26, 2020 10:12:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductSize generated by hbm2java
 */
public class ProductSize  implements java.io.Serializable {


     private Long id;
     private Product product;
     private Date createdAt;
     private Date updatedAt;
     private int quantity;
     private int size;
     private Set<CartItem> cartItems = new HashSet<CartItem>(0);
     private Set<OrderAppDetail> orderAppDetails = new HashSet<OrderAppDetail>(0);
     private Set<OrderWebsiteDetail> orderWebsiteDetails = new HashSet<OrderWebsiteDetail>(0);

    public ProductSize() {
    }

	
    public ProductSize(Product product, int quantity, int size) {
        this.product = product;
        this.quantity = quantity;
        this.size = size;
    }
    public ProductSize(Product product, Date createdAt, Date updatedAt, int quantity, int size, Set<CartItem> cartItems, Set<OrderAppDetail> orderAppDetails, Set<OrderWebsiteDetail> orderWebsiteDetails) {
       this.product = product;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.quantity = quantity;
       this.size = size;
       this.cartItems = cartItems;
       this.orderAppDetails = orderAppDetails;
       this.orderWebsiteDetails = orderWebsiteDetails;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public int getSize() {
        return this.size;
    }
    
    public void setSize(int size) {
        this.size = size;
    }
    public Set<CartItem> getCartItems() {
        return this.cartItems;
    }
    
    public void setCartItems(Set<CartItem> cartItems) {
        this.cartItems = cartItems;
    }
    public Set<OrderAppDetail> getOrderAppDetails() {
        return this.orderAppDetails;
    }
    
    public void setOrderAppDetails(Set<OrderAppDetail> orderAppDetails) {
        this.orderAppDetails = orderAppDetails;
    }
    public Set<OrderWebsiteDetail> getOrderWebsiteDetails() {
        return this.orderWebsiteDetails;
    }
    
    public void setOrderWebsiteDetails(Set<OrderWebsiteDetail> orderWebsiteDetails) {
        this.orderWebsiteDetails = orderWebsiteDetails;
    }




}


