package Model;
// Generated Mar 26, 2020 10:12:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Long id;
     private Date createdAt;
     private Date updatedAt;
     private String address;
     private Date dateOfBirth;
     private String email;
     private boolean isDelete;
     private String name;
     private String password;
     private String phone;
     private String role;
     private Set<OrderApp> orderApps = new HashSet<OrderApp>(0);
     private Set<OrderWebsite> orderWebsites = new HashSet<OrderWebsite>(0);
     private Set<Comment> comments = new HashSet<Comment>(0);
     private Set<CartItem> cartItems = new HashSet<CartItem>(0);

    public User() {
    }

	
    public User(boolean isDelete) {
        this.isDelete = isDelete;
    }
    public User(Date createdAt, Date updatedAt, String address, Date dateOfBirth, String email, boolean isDelete, String name, String password, String phone, String role, Set<OrderApp> orderApps, Set<OrderWebsite> orderWebsites, Set<Comment> comments, Set<CartItem> cartItems) {
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.address = address;
       this.dateOfBirth = dateOfBirth;
       this.email = email;
       this.isDelete = isDelete;
       this.name = name;
       this.password = password;
       this.phone = phone;
       this.role = role;
       this.orderApps = orderApps;
       this.orderWebsites = orderWebsites;
       this.comments = comments;
       this.cartItems = cartItems;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(boolean isDelete) {
        this.isDelete = isDelete;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public Set<OrderApp> getOrderApps() {
        return this.orderApps;
    }
    
    public void setOrderApps(Set<OrderApp> orderApps) {
        this.orderApps = orderApps;
    }
    public Set<OrderWebsite> getOrderWebsites() {
        return this.orderWebsites;
    }
    
    public void setOrderWebsites(Set<OrderWebsite> orderWebsites) {
        this.orderWebsites = orderWebsites;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }
    public Set<CartItem> getCartItems() {
        return this.cartItems;
    }
    
    public void setCartItems(Set<CartItem> cartItems) {
        this.cartItems = cartItems;
    }




}


