package Pojos;
// Generated Apr 23, 2020 4:34:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CartItem generated by hbm2java
 */
public class CartItem  implements java.io.Serializable {


     private Long id;
     private ProductSize productSize;
     private User user;
     private Date createdAt;
     private Date updatedAt;
     private int quantity;

    public CartItem() {
    }

	
    public CartItem(ProductSize productSize, User user, int quantity) {
        this.productSize = productSize;
        this.user = user;
        this.quantity = quantity;
    }
    public CartItem(ProductSize productSize, User user, Date createdAt, Date updatedAt, int quantity) {
       this.productSize = productSize;
       this.user = user;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.quantity = quantity;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public ProductSize getProductSize() {
        return this.productSize;
    }
    
    public void setProductSize(ProductSize productSize) {
        this.productSize = productSize;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


