package Pojos;
// Generated Apr 23, 2020 4:34:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Color generated by hbm2java
 */
public class Color  implements java.io.Serializable {


     private Long id;
     private Date createdAt;
     private Date updatedAt;
     private String code;
     private String name;
     private Set productColors = new HashSet(0);

    public Color() {
    }

	
    public Color(String name) {
        this.name = name;
    }
    public Color(Date createdAt, Date updatedAt, String code, String name, Set productColors) {
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.code = code;
       this.name = name;
       this.productColors = productColors;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProductColors() {
        return this.productColors;
    }
    
    public void setProductColors(Set productColors) {
        this.productColors = productColors;
    }




}


