package Pojos;
// Generated Apr 23, 2020 4:34:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DeliveryLog generated by hbm2java
 */
public class DeliveryLog  implements java.io.Serializable {


     private Long id;
     private OrderWeb orderWeb;
     private Date createdAt;
     private Date updatedAt;
     private String deliveryStatus;

    public DeliveryLog() {
    }

	
    public DeliveryLog(OrderWeb orderWeb, String deliveryStatus) {
        this.orderWeb = orderWeb;
        this.deliveryStatus = deliveryStatus;
    }
    public DeliveryLog(OrderWeb orderWeb, Date createdAt, Date updatedAt, String deliveryStatus) {
       this.orderWeb = orderWeb;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.deliveryStatus = deliveryStatus;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public OrderWeb getOrderWeb() {
        return this.orderWeb;
    }
    
    public void setOrderWeb(OrderWeb orderWeb) {
        this.orderWeb = orderWeb;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getDeliveryStatus() {
        return this.deliveryStatus;
    }
    
    public void setDeliveryStatus(String deliveryStatus) {
        this.deliveryStatus = deliveryStatus;
    }




}


