package Pojos;
// Generated Apr 23, 2020 4:34:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrderWeb generated by hbm2java
 */
public class OrderWeb  implements java.io.Serializable {


     private Long id;
     private User user;
     private Date createdAt;
     private Date updatedAt;
     private String consignee;
     private String consigneePhone;
     private String deliveryAddress;
     private String deliveryStatus;
     private String paymentMethod;
     private String paymentStatus;
     private long totalAmount;
     private Set orderWebDetails = new HashSet(0);
     private Set deliveryLogs = new HashSet(0);

    public OrderWeb() {
    }

	
    public OrderWeb(User user, String consignee, String consigneePhone, String deliveryAddress, String deliveryStatus, String paymentMethod, String paymentStatus, long totalAmount) {
        this.user = user;
        this.consignee = consignee;
        this.consigneePhone = consigneePhone;
        this.deliveryAddress = deliveryAddress;
        this.deliveryStatus = deliveryStatus;
        this.paymentMethod = paymentMethod;
        this.paymentStatus = paymentStatus;
        this.totalAmount = totalAmount;
    }
    public OrderWeb(User user, Date createdAt, Date updatedAt, String consignee, String consigneePhone, String deliveryAddress, String deliveryStatus, String paymentMethod, String paymentStatus, long totalAmount, Set orderWebDetails, Set deliveryLogs) {
       this.user = user;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.consignee = consignee;
       this.consigneePhone = consigneePhone;
       this.deliveryAddress = deliveryAddress;
       this.deliveryStatus = deliveryStatus;
       this.paymentMethod = paymentMethod;
       this.paymentStatus = paymentStatus;
       this.totalAmount = totalAmount;
       this.orderWebDetails = orderWebDetails;
       this.deliveryLogs = deliveryLogs;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getConsignee() {
        return this.consignee;
    }
    
    public void setConsignee(String consignee) {
        this.consignee = consignee;
    }
    public String getConsigneePhone() {
        return this.consigneePhone;
    }
    
    public void setConsigneePhone(String consigneePhone) {
        this.consigneePhone = consigneePhone;
    }
    public String getDeliveryAddress() {
        return this.deliveryAddress;
    }
    
    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }
    public String getDeliveryStatus() {
        return this.deliveryStatus;
    }
    
    public void setDeliveryStatus(String deliveryStatus) {
        this.deliveryStatus = deliveryStatus;
    }
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public String getPaymentStatus() {
        return this.paymentStatus;
    }
    
    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }
    public long getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(long totalAmount) {
        this.totalAmount = totalAmount;
    }
    public Set getOrderWebDetails() {
        return this.orderWebDetails;
    }
    
    public void setOrderWebDetails(Set orderWebDetails) {
        this.orderWebDetails = orderWebDetails;
    }
    public Set getDeliveryLogs() {
        return this.deliveryLogs;
    }
    
    public void setDeliveryLogs(Set deliveryLogs) {
        this.deliveryLogs = deliveryLogs;
    }




}


