package Pojos;
// Generated Apr 23, 2020 4:34:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrderApp generated by hbm2java
 */
public class OrderApp  implements java.io.Serializable {


     private Long id;
     private User user;
     private Date createdAt;
     private Date updatedAt;
     private long totalAmount;
     private String status;
     private Set orderAppDetails = new HashSet(0);

    public OrderApp() {
    }

	
    public OrderApp(User user, long totalAmount, String status) {
        this.user = user;
        this.totalAmount = totalAmount;
        this.status = status;
    }
    public OrderApp(User user, Date createdAt, Date updatedAt, long totalAmount, String status, Set orderAppDetails) {
       this.user = user;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.totalAmount = totalAmount;
       this.status = status;
       this.orderAppDetails = orderAppDetails;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public long getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(long totalAmount) {
        this.totalAmount = totalAmount;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getOrderAppDetails() {
        return this.orderAppDetails;
    }
    
    public void setOrderAppDetails(Set orderAppDetails) {
        this.orderAppDetails = orderAppDetails;
    }




}


