package Pojos;
// Generated Apr 23, 2020 4:34:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Long id;
     private Brand brand;
     private Category category;
     private Date createdAt;
     private Date updatedAt;
     private String description;
     private boolean isDelete;
     private String name;
     private long price;
     private String status;
     private String versionName;
     private Set productReviews = new HashSet(0);
     private Set productSizes = new HashSet(0);
     private Set productViews = new HashSet(0);
     private Set productImages = new HashSet(0);
     private Set userWishlists = new HashSet(0);
     private Set productColors = new HashSet(0);

    public Product() {
    }

	
    public Product(Brand brand, Category category, boolean isDelete, String name, long price, String status) {
        this.brand = brand;
        this.category = category;
        this.isDelete = isDelete;
        this.name = name;
        this.price = price;
        this.status = status;
    }
    public Product(Brand brand, Category category, Date createdAt, Date updatedAt, String description, boolean isDelete, String name, long price, String status, String versionName, Set productReviews, Set productSizes, Set productViews, Set productImages, Set userWishlists, Set productColors) {
       this.brand = brand;
       this.category = category;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.description = description;
       this.isDelete = isDelete;
       this.name = name;
       this.price = price;
       this.status = status;
       this.versionName = versionName;
       this.productReviews = productReviews;
       this.productSizes = productSizes;
       this.productViews = productViews;
       this.productImages = productImages;
       this.userWishlists = userWishlists;
       this.productColors = productColors;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public boolean isIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(boolean isDelete) {
        this.isDelete = isDelete;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public long getPrice() {
        return this.price;
    }
    
    public void setPrice(long price) {
        this.price = price;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getVersionName() {
        return this.versionName;
    }
    
    public void setVersionName(String versionName) {
        this.versionName = versionName;
    }
    public Set getProductReviews() {
        return this.productReviews;
    }
    
    public void setProductReviews(Set productReviews) {
        this.productReviews = productReviews;
    }
    public Set getProductSizes() {
        return this.productSizes;
    }
    
    public void setProductSizes(Set productSizes) {
        this.productSizes = productSizes;
    }
    public Set getProductViews() {
        return this.productViews;
    }
    
    public void setProductViews(Set productViews) {
        this.productViews = productViews;
    }
    public Set getProductImages() {
        return this.productImages;
    }
    
    public void setProductImages(Set productImages) {
        this.productImages = productImages;
    }
    public Set getUserWishlists() {
        return this.userWishlists;
    }
    
    public void setUserWishlists(Set userWishlists) {
        this.userWishlists = userWishlists;
    }
    public Set getProductColors() {
        return this.productColors;
    }
    
    public void setProductColors(Set productColors) {
        this.productColors = productColors;
    }




}


