package Pojos;
// Generated Apr 23, 2020 4:34:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductSize generated by hbm2java
 */
public class ProductSize  implements java.io.Serializable {


     private Long id;
     private Product product;
     private Date createdAt;
     private Date updatedAt;
     private int quantity;
     private int size;
     private Set orderWebDetails = new HashSet(0);
     private Set cartItems = new HashSet(0);
     private Set orderAppDetails = new HashSet(0);

    public ProductSize() {
    }

	
    public ProductSize(Product product, int quantity, int size) {
        this.product = product;
        this.quantity = quantity;
        this.size = size;
    }
    public ProductSize(Product product, Date createdAt, Date updatedAt, int quantity, int size, Set orderWebDetails, Set cartItems, Set orderAppDetails) {
       this.product = product;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.quantity = quantity;
       this.size = size;
       this.orderWebDetails = orderWebDetails;
       this.cartItems = cartItems;
       this.orderAppDetails = orderAppDetails;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public int getSize() {
        return this.size;
    }
    
    public void setSize(int size) {
        this.size = size;
    }
    public Set getOrderWebDetails() {
        return this.orderWebDetails;
    }
    
    public void setOrderWebDetails(Set orderWebDetails) {
        this.orderWebDetails = orderWebDetails;
    }
    public Set getCartItems() {
        return this.cartItems;
    }
    
    public void setCartItems(Set cartItems) {
        this.cartItems = cartItems;
    }
    public Set getOrderAppDetails() {
        return this.orderAppDetails;
    }
    
    public void setOrderAppDetails(Set orderAppDetails) {
        this.orderAppDetails = orderAppDetails;
    }




}


