package Pojos;
// Generated Apr 23, 2020 4:34:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProductView generated by hbm2java
 */
public class ProductView  implements java.io.Serializable {


     private Long id;
     private Product product;
     private User user;
     private Date createdAt;
     private Date updatedAt;

    public ProductView() {
    }

	
    public ProductView(Product product) {
        this.product = product;
    }
    public ProductView(Product product, User user, Date createdAt, Date updatedAt) {
       this.product = product;
       this.user = user;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


