package Pojos;
// Generated Apr 23, 2020 4:34:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProductReview generated by hbm2java
 */
public class ProductReview  implements java.io.Serializable {


     private Long id;
     private Product product;
     private User user;
     private Date createdAt;
     private Date updatedAt;
     private String content;
     private Short rating;
     private String title;

    public ProductReview() {
    }

	
    public ProductReview(Product product, User user, String content) {
        this.product = product;
        this.user = user;
        this.content = content;
    }
    public ProductReview(Product product, User user, Date createdAt, Date updatedAt, String content, Short rating, String title) {
       this.product = product;
       this.user = user;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.content = content;
       this.rating = rating;
       this.title = title;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Short getRating() {
        return this.rating;
    }
    
    public void setRating(Short rating) {
        this.rating = rating;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }




}


